# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideogamesArchive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideogamesArchive
  pod 'Moya'
  pod 'Kingfisher', '~> 4.6.1'
  pod 'KVNProgress', '~> 2.3.1'
  pod 'RealmSwift', '~> 3.0.2'

end
